# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-05 22:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True


    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=5000)),
                ('text_html', models.CharField(blank=True, max_length=5000)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('flagged_by', models.ManyToManyField(blank=True, null=True, related_name='flagged_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=120)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('looking_for_admin', models.BooleanField(default=False)),
                ('description_html', models.TextField(blank=True)),
                ('description_markdown', models.TextField(blank=True)),
                ('showcase_html', models.TextField(blank=True)),
                ('showcase_markdown', models.TextField(blank=True)),
                ('hour_estimate', models.PositiveIntegerField(default=2)),
                ('pub_date', models.DateTimeField()),
                ('p_completed', models.BooleanField(default=False)),
                ('wont_be_completed', models.BooleanField(default=False)),
                ('score_proposed', models.FloatField(default=0.0)),
                ('score_completed', models.FloatField(default=0.0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_authored', to=settings.AUTH_USER_MODEL)),
                ('completed_votes', models.ManyToManyField(blank=True, null=True, related_name='projects_completed_votes', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, related_name='projects_event', to='eventapp.Event')),
                ('members', models.ManyToManyField(related_name='projects_joined', through='projects.Membership', to=settings.AUTH_USER_MODEL)),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_proposed', to=settings.AUTH_USER_MODEL)),
                ('proposed_votes', models.ManyToManyField(blank=True, null=True, related_name='projects_proposed_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proposed_Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects.Project', unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
